version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: billable_metrics_pg
    restart: always
    environment:
      POSTGRES_DB: billable_metrics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
